/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maytinh02;

/**
 *
 * @author thien
 */
public class MayTinh02 extends javax.swing.JFrame {

    /**
     * Creates new form MayTinh02
     */
    public double aNum,

    /**
     * Creates new form MayTinh02
     */
    kq;
    public String dau;
    public MayTinh02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hienThi1 = new javax.swing.JLabel();
        hienThi2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        so7 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        so1 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        so0 = new javax.swing.JButton();
        bang = new javax.swing.JButton();
        chia = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(318, 417));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("T H Y Đ T");

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        hienThi1.setBackground(new java.awt.Color(255, 255, 255));
        hienThi1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        hienThi1.setForeground(new java.awt.Color(102, 102, 102));
        hienThi1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hienThi1.setOpaque(true);
        hienThi1.setPreferredSize(new java.awt.Dimension(34, 35));

        hienThi2.setBackground(new java.awt.Color(255, 255, 255));
        hienThi2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        hienThi2.setForeground(new java.awt.Color(153, 153, 153));
        hienThi2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hienThi2.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hienThi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hienThi2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hienThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(hienThi2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 3, 3));

        so7.setBackground(new java.awt.Color(255, 255, 255));
        so7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so7.setForeground(new java.awt.Color(255, 153, 51));
        so7.setText("7");
        so7.setBorderPainted(false);
        so7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so7);

        so8.setBackground(new java.awt.Color(255, 255, 255));
        so8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so8.setForeground(new java.awt.Color(255, 153, 51));
        so8.setText("8");
        so8.setBorderPainted(false);
        so8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so8);

        so9.setBackground(new java.awt.Color(255, 255, 255));
        so9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so9.setForeground(new java.awt.Color(255, 153, 51));
        so9.setText("9");
        so9.setBorderPainted(false);
        so9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so9);

        cong.setBackground(new java.awt.Color(255, 153, 51));
        cong.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cong.setForeground(new java.awt.Color(255, 255, 255));
        cong.setText("+");
        cong.setBorderPainted(false);
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel2.add(cong);

        so4.setBackground(new java.awt.Color(255, 255, 255));
        so4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so4.setForeground(new java.awt.Color(255, 153, 51));
        so4.setText("4");
        so4.setBorderPainted(false);
        so4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so4);

        so5.setBackground(new java.awt.Color(255, 255, 255));
        so5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so5.setForeground(new java.awt.Color(255, 153, 51));
        so5.setText("5");
        so5.setBorderPainted(false);
        so5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so5);

        so6.setBackground(new java.awt.Color(255, 255, 255));
        so6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so6.setForeground(new java.awt.Color(255, 153, 51));
        so6.setText("6");
        so6.setBorderPainted(false);
        so6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so6);

        tru.setBackground(new java.awt.Color(255, 153, 51));
        tru.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tru.setForeground(new java.awt.Color(255, 255, 255));
        tru.setText("-");
        tru.setBorderPainted(false);
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel2.add(tru);

        so1.setBackground(new java.awt.Color(255, 255, 255));
        so1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so1.setForeground(new java.awt.Color(255, 153, 51));
        so1.setText("1");
        so1.setBorderPainted(false);
        so1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so1);

        so2.setBackground(new java.awt.Color(255, 255, 255));
        so2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so2.setForeground(new java.awt.Color(255, 153, 51));
        so2.setText("2");
        so2.setBorderPainted(false);
        so2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so2);

        so3.setBackground(new java.awt.Color(255, 255, 255));
        so3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        so3.setForeground(new java.awt.Color(255, 153, 51));
        so3.setText("3");
        so3.setBorderPainted(false);
        so3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so3);

        nhan.setBackground(new java.awt.Color(255, 153, 51));
        nhan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nhan.setForeground(new java.awt.Color(255, 255, 255));
        nhan.setText("x");
        nhan.setBorderPainted(false);
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel2.add(nhan);

        xoa.setBackground(new java.awt.Color(255, 153, 51));
        xoa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        xoa.setForeground(new java.awt.Color(255, 255, 255));
        xoa.setText("C");
        xoa.setBorderPainted(false);
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        jPanel2.add(xoa);

        so0.setBackground(new java.awt.Color(255, 153, 51));
        so0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        so0.setForeground(new java.awt.Color(255, 255, 255));
        so0.setText("0");
        so0.setBorderPainted(false);
        so0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPanel2.add(so0);

        bang.setBackground(new java.awt.Color(255, 153, 51));
        bang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bang.setForeground(new java.awt.Color(255, 255, 255));
        bang.setText("=");
        bang.setBorderPainted(false);
        bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangActionPerformed(evt);
            }
        });
        jPanel2.add(bang);

        chia.setBackground(new java.awt.Color(255, 153, 51));
        chia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        chia.setForeground(new java.awt.Color(255, 255, 255));
        chia.setText("/");
        chia.setBorderPainted(false);
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPanel2.add(chia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void so1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so1ActionPerformed
        String cmd = evt.getActionCommand();
        hienThi1.setText(hienThi1.getText() + cmd);
    }//GEN-LAST:event_so1ActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        hienThi1.setText("");
        hienThi2.setText("");
    }//GEN-LAST:event_xoaActionPerformed

    private void bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangActionPerformed
        String ht1 = hienThi1.getText();
        if(ht1.isEmpty())
            hienThi2.setText("0");
        if(ht1.contains("+/") || ht1.contains("-/")
        || ht1.contains("-x") || ht1.contains("+x")
        || ht1.contains("x/") || ht1.contains("/x"))
            hienThi2.setText("Chồng phép tính");
        switch(dau) {
            case "+":
                kq = aNum + Double.parseDouble(ht1);
                break;
            case "-":
                kq = aNum - Double.parseDouble(ht1);
                break;
            case "x": 
                kq = aNum * Double.parseDouble(ht1);
                break;
            case "/": 
                kq = aNum / Double.parseDouble(ht1);
                break;
        }
        hienThi1.setText(String.valueOf(kq)); 
    }//GEN-LAST:event_bangActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
        String cmd = evt.getActionCommand();
        switch(cmd) {
            case "+": aNum = Double.parseDouble(hienThi1.getText()); dau = "+"; break;
            case "-": aNum = Double.parseDouble(hienThi1.getText()); dau = "-"; break;
            case "x": aNum = Double.parseDouble(hienThi1.getText()); dau = "x"; break;
            case "/": aNum = Double.parseDouble(hienThi1.getText()); dau = "/"; break;
        }
        hienThi1.setText("");
        hienThi2.setText(cmd);
    }//GEN-LAST:event_congActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MayTinh02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MayTinh02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MayTinh02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MayTinh02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MayTinh02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bang;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JLabel hienThi1;
    private javax.swing.JLabel hienThi2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nhan;
    private javax.swing.JButton so0;
    private javax.swing.JButton so1;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    private javax.swing.JButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
